<?php

/**
 * @file
 * Contains ax_custom_node_details.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function ax_custom_node_details_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ax_custom_node_details module.
    case 'help.page.ax_custom_node_details':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module is used for fetching the node details depend on the Site API key') . '</p>';
      return $output;

    default:
  }
}
